

all:
	
clean:
	find ../ -name "*~" | xargs rm -rf 
	find ../ -name "*pdf" | xargs rm -rf 
	find ../ -name "*tex" | xargs rm -rf
	find ../ -name "_minted*" | xargs rm -rf
	find ../ -name "auto" | xargs rm -rf
	rm -rf *lol *lot *bbl
