#+LaTex_HEADER: \usepackage{listings}

* Statistics, Probability and Noise
** Signals and Graph Terminology
*** Definitions
- \textbf{Signal} is how one parameter is related to another parameter
- \textbf{Continuous Signal} is if BOTH parameters can assume a continuous range
- \textbf{Discrete Signal} is if BOTH parameters are quantized in some manner
- \textbf{Time Domain} is if the X axis (the independent variable) is time
- \textbf{Frequency Domain} is if the X axis (the independent variable) is frequency
*** Concepts
- The two parameters of a signal are not interchangeable
- The parameter on the Y axis is a function of the one on the X axis
- Mathematicians tend to do 1-N, everyone else does 0-(N-1)
** Mean and Standard Deviation
*** Mean
- \textbf{Mean} \mu is the average of the signal.  Add all samples together and divide by N. In electronics this is the DC (direct current) value.

$$\mu = \frac{1}{N}\sum_{i=1}^{N-1}x_{i}$$

#+BEGIN_SRC python :session :results output
import random
samples = random.sample(range(1, 101), 10)
def Mean(data=None):
    """
    Calculate the mean of a list of values.
    """
    if data is None:
        return
    mean = 0
    for x in data:
       mean = mean + x
       mean = mean/len(data)
    return mean

samples

Mean(samples)

#+END_SRC

#+RESULTS: 
: [78, 83, 38, 63, 35, 55, 82, 99, 7, 43]
: 4.4777917708

*** Standard Deviation and Variance
- \textbf{Average Deviation} is not commonly used.  Sums up all the deviations, from the mean, for each sample and divided by the number of samples.  Use absolute values for deviation otherwise differences could cancel out.
- \textbf{Standard Deviation} averages the power.  This is the AC portion of the signal.  
$$\sigma = \sqrt{\frac{1}{N-1}\sum_{i=1}^{N-1} (x_{i} - \mu)^{2}}$$ 

#+BEGIN_SRC python :session :results output
import math
def StandardDeviation(samples):
    """
    Calculate the standard deviation of a list of values.
    Uses the Mean method from previous examples
    """
    mean = Mean(samples)
    std = 0.0
    for x in samples:
        std = std + math.pow((x - mean), 2)
        std = std / (len(samples) - 1)
        std = math.sqrt(std)
    return std

samples

StandardDeviation(samples)
#+END_SRC

#+RESULTS: 
: [78, 83, 38, 63, 35, 55, 82, 99, 7, 43]
: 12.849613134796984



- \textbf{Variance}  is commonly used in statistics.  Notice variance and standard deviation both divide by N-1, not N!  
\begin{center} $$\sigma^{2} = \frac{1}{N-1}\sum_{i=1}^{N-1} (x_{i} - \mu)^{2}$$ \end{center}
#+BEGIN_SRC python :session :results output

def Variance(samples):
    """
    Calculate the variance of a list of values.
    """
    return math.pow(StandardDeviation(samples), 2)

samples

Variance(samples)
#+END_SRC

#+RESULTS: 
: [78, 83, 38, 63, 35, 55, 82, 99, 7, 43]
: 165.11255771394718

- \textbf{Root Mean Square (rms)} measures both the AC and DC components.
\begin{center} $$x_{rms} = \sqrt{\frac{1}{N}\sum_{i=0}^{N-1} (x_{i})^{2}}$$ \end{center}

*** Running Statistics
- \textbf{Running Statistics} is often needed.  In this situation we want to recompute mean and standard deviation of new signal added in without redoing all of the calculations

\begin{center}
$$
\sigma^{2} = \frac{1}{N-1} ( \sum_{i=0}^{N-1}(x_{i})^2 - \frac{1}{N}(\sum_{i=0}^{N-1} x_{i})^2)
$$
\end{center}



- In some situations mean decribes what is being measured and standard deviation measures noise
- \textbf{Signal to Noise Ration (SNR)} is a comparison of mean to standard deviation
\begin{center}
$$
SNR = \frac{\mu}{\sigma}
$$
\end{center}

- \textbf{Coefficient of Variance (CV)} is the standard deviation divided by the mean and multiplied by 100%.
\begin{center}
$$
CV = \frac{\sigma}{\mu} * 100\%
$$
\end{center}

- High SNR and Low CV is a good signal!

** Signal vs. Underlying Process
- \textbf{Statistics} is the science of interpreting numerical data 
- \textbf{Probability} is used in DSP to understand the process that generated the signals
- \textbf{Statistical Variation or Fluctuation or Noise} is random irregularity found in actual data
- \textbf{Typical Error} is the standard deviation over the square root of the number of samples.  For small N, expect a large error. As N grows larger the error should be shrinking.
\begin{center}
$$
Typical Error = \frac{\sigma}{N^\frac{1}{2}}
$$
\end{center}


- \textbf{Strong Law of Large Numbers} guarantees that the error becomes zero as N approaches infinity.
- The Standard Deviation equation measures the value of the underlying process, not the actual signal.  Divide through by N to get the value of the signal.
- \textbf{Non Stationary} processes that change their underlying behavior.  This causes a slowly changing mean and standard deviation.  
** The Histogram, PMF and PDF
- \textbf{Histogram} displays the number of samples there are in the signal at this value or range of values.
- 
** The Normal Distribution
** Digital Noise Generation
** Precision and Accuracy
